export type ExceptionEvents =
  'DATABASE_READ_FAILED'
  | 'DATABASE_WRITE_FAILED'
  | 'API_REQUEST_FAILED'
  | 'S3_FETCH_FAILED'
  | 'S3_PUT_FAILED'
  | 'UNEXPECTED_EXCEPTION'
  | 'EVENT_BRIDGE_TRIGGER_FAILED'
